### ISSUE TITLE
Doesn't register QuestComplete

### ISSUE THREAD

**Issue by Ryuichiro** [TheNoobCompany/WorldQuestTNB#3]
The Bot won't register that a World Quest was completed.
In [this](http://thenoobbot.com/community/attachment.php?aid=237) example the quest (Gather 10 special herbs) was already partially done.
After starting the profile he gathered the remaining herbs and gets his reward at 02:57:44.
But he continues looking for more special herbs, which are phased out for the player because the quest is complete.
Restarting fixes the issue because he then checks the quest which is not available.

**Comment by mmalka** [comment]
I'll see what can be done

**Comment by mmalka** [comment]
Should be fine by the next update.
