### ISSUE TITLE
"UseActionButtonOnUnit" not a valid objective on "Withered Wrangling: Meredil and Ambervale" in suramar

### ISSUE THREAD

**Issue by leniver** [TheNoobCompany/WorldQuestTNB#5]

**Comment by leniver** [comment]
I commented the quest on last commit
https://github.com/TheNoobCompany/WorldQuestTNB/commit/fa48e1d733089d1270904cca8071bca92a328ffc

**Comment by Ryuichiro** [comment]
I think Vesper wanted to add support in the next update.

**Comment by mmalka** [comment]
Because of this: https://github.com/TheNoobCompany/WorldQuestTNB/commit/982d9317b9fddd16eaed4d7b4bf9a1cf1611ba26

Wrong Objective : New Objective requires BotUpdate.

**Comment by mmalka** [comment]
Updated in 6.2.7+

**Comment by leniver** [comment]
Great! Thanks
