### ISSUE TITLE
Suggestion: Flight Master

### ISSUE THREAD

**Issue by golgolak** [TheNoobCompany/WorldQuestTNB#7]
Hi,

Is it possible to use Flight Masters and Flight Master Whistle to go around the zone? Thanks

**Comment by mmalka** [comment]
This is indeed in project, I need to import the Taxi code from Archaeologist.. properly.

**Comment by mmalka** [comment]
This is coming in the next TNB update, I ran few test, working fine.

**Comment by leniver** [comment]
Tested, It works well! Great job!
